---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: minecraft-storage
  hostPath:
    path: "/opt/minecraft/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minecraft-storage 
  resources:
    requests:
      storage: 10Gi
